/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnibwapi_model_Unit */

#ifndef _Included_jnibwapi_model_Unit
#define _Included_jnibwapi_model_Unit
#ifdef __cplusplus
extern "C" {
#endif
#undef jnibwapi_model_Unit_numAttributes
#define jnibwapi_model_Unit_numAttributes 118L
#undef jnibwapi_model_Unit_TO_DEGREES
#define jnibwapi_model_Unit_TO_DEGREES 57.29577951308232
#undef jnibwapi_model_Unit_fixedScale
#define jnibwapi_model_Unit_fixedScale 100.0
/*
 * Class:     jnibwapi_model_Unit
 * Method:    attack
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_attack__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    attack
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_attack__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    build
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_build
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    buildAddon
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_buildAddon
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    train
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_train
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    morph
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_morph
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    research
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_research
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    upgrade
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_upgrade
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    setRallyPoint
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_setRallyPoint__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    setRallyPoint
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_setRallyPoint__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    move
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_move
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    patrol
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_patrol
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    holdPosition
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_holdPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    stop
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_stop
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    follow
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_follow
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    gather
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_gather
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    returnCargo
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_returnCargo
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    repair
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_repair
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    burrow
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_burrow
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    unburrow
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_unburrow
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    cloak
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_cloak
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    decloak
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_decloak
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    siege
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_siege
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    unsiege
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_unsiege
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    lift
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_lift
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    land
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_land
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    load
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_load
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    unload
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_unload
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    unloadAll
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_unloadAll__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    unloadAll
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_unloadAll__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    rightClick
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_rightClick__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    rightClick
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_rightClick__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    haltConstruction
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_haltConstruction
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    cancelConstruction
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_cancelConstruction
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    cancelAddon
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_cancelAddon
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    cancelTrain
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_cancelTrain
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    cancelMorph
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_cancelMorph
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    cancelResearch
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_cancelResearch
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    cancelUpgrade
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_cancelUpgrade
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    useTech
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_useTech__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    useTech
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_useTech__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    useTech
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_useTech__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jnibwapi_model_Unit
 * Method:    placeCOP
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_model_Unit_placeCOP
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
