/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnibwapi_Broodwar */

#ifndef _Included_jnibwapi_Broodwar
#define _Included_jnibwapi_Broodwar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnibwapi_Broodwar
 * Method:    startClient
 * Signature: (Ljnibwapi/Broodwar;)V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_startClient
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getFrame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnibwapi_Broodwar_getFrame
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getReplayFrameTotal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnibwapi_Broodwar_getReplayFrameTotal
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getPlayersData
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getPlayersData
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getPlayerUpdate
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getPlayerUpdate
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getPlayerName
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jnibwapi_Broodwar_getPlayerName
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getResearchStatus
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getResearchStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getUpgradeStatus
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getUpgradeStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getAllUnitsData
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getAllUnitsData
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getRaceTypes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getRaceTypes
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getRaceTypeName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnibwapi_Broodwar_getRaceTypeName
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getUnitTypes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getUnitTypes
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getUnitTypeName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnibwapi_Broodwar_getUnitTypeName
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getRequiredUnits
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getRequiredUnits
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getTechTypes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getTechTypes
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getTechTypeName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnibwapi_Broodwar_getTechTypeName
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getUpgradeTypes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getUpgradeTypes
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getUpgradeTypeName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnibwapi_Broodwar_getUpgradeTypeName
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getWeaponTypes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getWeaponTypes
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getWeaponTypeName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnibwapi_Broodwar_getWeaponTypeName
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getUnitSizeTypes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getUnitSizeTypes
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getUnitSizeTypeName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnibwapi_Broodwar_getUnitSizeTypeName
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getBulletTypes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getBulletTypes
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getBulletTypeName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnibwapi_Broodwar_getBulletTypeName
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getDamageTypes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getDamageTypes
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getDamageTypeName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnibwapi_Broodwar_getDamageTypeName
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getExplosionTypes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getExplosionTypes
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getExplosionTypeName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnibwapi_Broodwar_getExplosionTypeName
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getUnitCommandTypes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getUnitCommandTypes
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getUnitCommandTypeName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnibwapi_Broodwar_getUnitCommandTypeName
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getOrderTypes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getOrderTypes
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getOrderTypeName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnibwapi_Broodwar_getOrderTypeName
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getUnitIdsOnTile
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getUnitIdsOnTile
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    analyzeTerrain
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_analyzeTerrain
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getMapWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnibwapi_Broodwar_getMapWidth
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getMapHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnibwapi_Broodwar_getMapHeight
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getMapName
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_jnibwapi_Broodwar_getMapName
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getMapFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnibwapi_Broodwar_getMapFileName
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getMapHash
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnibwapi_Broodwar_getMapHash
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getHeightData
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getHeightData
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getRegionMap
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getRegionMap
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getWalkableData
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getWalkableData
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getBuildableData
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getBuildableData
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getChokePoints
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getChokePoints
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getRegions
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getRegions
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getPolygon
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getPolygon
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getBaseLocations
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jnibwapi_Broodwar_getBaseLocations
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    drawHealth
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_drawHealth
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    drawTargets
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_drawTargets
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    drawIDs
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_drawIDs
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    enableUserInput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_enableUserInput
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    enablePerfectInformation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_enablePerfectInformation
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    setGameSpeed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_setGameSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    setFrameSkip
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_setFrameSkip
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    leaveGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_leaveGame
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    drawBox
 * Signature: (IIIIIZZ)V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_drawBox
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    drawCircle
 * Signature: (IIIIZZ)V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_drawCircle
  (JNIEnv *, jobject, jint, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    drawLine
 * Signature: (IIIIIZ)V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_drawLine
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    drawDot
 * Signature: (IIIZ)V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_drawDot
  (JNIEnv *, jobject, jint, jint, jint, jboolean);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    drawText
 * Signature: (IILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_drawText
  (JNIEnv *, jobject, jint, jint, jstring, jboolean);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    isVisible
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_isVisible
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    isExplored
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_isExplored
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    isBuildable
 * Signature: (IIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_isBuildable
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    hasCreep
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_hasCreep
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    hasPower
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_hasPower__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    hasPower
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_hasPower__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    hasPower
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_hasPower__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    hasPower
 * Signature: (IIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_hasPower__IIIII
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    hasPowerPrecise
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_hasPowerPrecise
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    hasPath
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_hasPath__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    hasPath
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_hasPath__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    hasPath
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_hasPath__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    hasLoadedUnit
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_hasLoadedUnit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    canBuildHere
 * Signature: (IIIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_canBuildHere__IIIZ
  (JNIEnv *, jobject, jint, jint, jint, jboolean);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    canBuildHere
 * Signature: (IIIIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_canBuildHere__IIIIZ
  (JNIEnv *, jobject, jint, jint, jint, jint, jboolean);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    canMake
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_canMake__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    canMake
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_canMake__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    canResearch
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_canResearch__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    canResearch
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_canResearch__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    canUpgrade
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_canUpgrade__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    canUpgrade
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_canUpgrade__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    printText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_printText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    sendText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_sendText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    setCommandOptimizationLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jnibwapi_Broodwar_setCommandOptimizationLevel
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    isReplay
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_isReplay
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    isVisibleToPlayer
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jnibwapi_Broodwar_isVisibleToPlayer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnibwapi_Broodwar_getLastError
  (JNIEnv *, jobject);

/*
 * Class:     jnibwapi_Broodwar
 * Method:    getRemainingLatencyFrames
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnibwapi_Broodwar_getRemainingLatencyFrames
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
